development:
  adapter: postgresql
  encoding: unicode
  username: rails
  password: rails
  database: wehirefitness
  pool: 5
  timeout: 5000


test: &test
  adapter: postgresql
  encoding: unicode
  database: wehirefitness_test
  host: localhost
  pool: 5
  username: rails
  password: rails

cucumber:
  <<: *test


